import { RouteInfo } from './sidebar.metadata';

export const ROUTES_ADMIN: RouteInfo[] = [
  // {
  //   path: '/admin/home-admin',
  //   title: 'MENUITEMS.HOME.TEXT',
  //   iconType: 'feather',
  //   icon: 'home',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  {
    path: '/admin/users-management',
    title: 'MENUITEMS.USERS-MANAGEMENT.TEXT',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/logs-management',
    title: 'MENUITEMS.LOGS-MANAGEMENT.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/testimonials-management',
    title: 'MENUITEMS.TESTIMONIALS-MANAGEMENT.TEXT',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/products-management',
    title: 'MENUITEMS.PRODUCTS-MANAGEMENT.TEXT',
    iconType: 'feather',
    icon: 'package',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
];
